version: '3.8'

services:
  crypto-database:
    image: mysql:8.0
    container_name: crypto-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    volumes:
      - crypto-data:/var/lib/mysql
    restart: always

  crypto-backend:
    build:
      context: .
    container_name: crypto-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://crypto-database:3306/crypto_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    depends_on:
      - crypto-database
    restart: always

volumes:
  crypto-data: